### ISSUE TITLE
Hướng dẫn kết nối chân giữa module sim với esp

### ISSUE THREAD

**Issue by trieu94** [khoih-prog/Blynk_Async_GSM_Manager#1]
Mình chỉ thấy define các chân nhưng các module sim nhiều loại. Vậy sơ đồ kết nối thế nào có thể hướng dẫn được không ạ, thanks a!!

**Comment by trieu94** [comment]
![IMG_UPLOAD_20201229_121616.jpg](https://user-images.githubusercontent.com/52556872/103324872-b4390280-4a7b-11eb-8981-fd045de3d731.jpg) chưa rõ chỗ kết nối này ạ

**Comment by khoih-prog** [comment]
Translation into English

> Guide to connect between SIM modules and ESP 

There are hundreds of different type of SIM module on the market.

You have to read and understand the corresponding **SIM's data sheets**, then test to be sure **it's working OK** by using the simplest programs possible before moving into more complex applications.

Basically, the majority of SIM modules are using Serial Port to communicate with the MCU (ESP, AVR, etc.) and you can use either `Hardware/Software Serial`. You also have to deal with other pins, such as RST, PWKEY, POWER_ON, etc.

See [**TinyGSM's AllFunctions example**](https://github.com/vshymanskyy/TinyGSM/blob/master/examples/AllFunctions/AllFunctions.ino#L33-L52)

```
// Set serial for debug console (to the Serial Monitor, default speed 115200)
#define SerialMon Serial

// Set serial for AT commands (to the module)
// Use Hardware Serial on Mega, Leonardo, Micro
#define SerialAT Serial1

// or Software Serial on Uno, Nano
// #include <SoftwareSerial.h>
// SoftwareSerial SerialAT(2, 3);  // RX, TX

// See all AT commands, if wanted
// #define DUMP_AT_COMMANDS

// Define the serial console for debug prints, if needed
#define TINY_GSM_DEBUG SerialMon

// Range to attempt to autobaud
#define GSM_AUTOBAUD_MIN 9600
#define GSM_AUTOBAUD_MAX 57600
```

The [**Blynk_Async_GSM_Manager examples**](https://github.com/khoih-prog/Blynk_Async_GSM_Manager/tree/master/examples) are written for TTGO T-Call, and you can try to use the same pin-to-pin connections to see if OK

```
// TTGO T-Call pin definitions
#define MODEM_RST            5
#define MODEM_PWKEY          4
#define MODEM_POWER_ON       23

#define MODEM_TX             27
#define MODEM_RX             26

#define I2C_SDA              21
#define I2C_SCL              22
```



Then apply those working pin-to-pin connections into this multi-function and more complex [**Blynk_Async_GSM_Manager library**](https://github.com/khoih-prog/Blynk_Async_GSM_Manager). This question has nothing to do with this library.

Have some time to do research and test at

1. [**TinyGSM Library**](https://github.com/vshymanskyy/TinyGSM)
2. [**Board Configuration**](https://github.com/vshymanskyy/TinyGSM/wiki/Board-configuration)
3. Using these [**TinyGSM examples**](https://github.com/vshymanskyy/TinyGSM/tree/master/examples)
4. Especially [**BlynkClient example**](https://github.com/vshymanskyy/TinyGSM/tree/master/examples/BlynkClient)

I certainly wish I have all the time in the world to spend to compensate the time you should spend for basic  researching.

Good Luck,
