### ISSUE TITLE
AsyncWebServer on GSM connection. Is possible?

### ISSUE THREAD

**Issue by woodlist** [khoih-prog/Blynk_Async_GSM_Manager#2]
This is not issue, but a question. Is it possible to get organized such a web server on GSM/GPRS connection. The WiFi is not required to be in use. Please, introduce an simple "Hello World" web page, with for example, Sim800l modem. I know, each connection sessions gives newer IP to the connected client. So, additional implementation of dealing with this host by EasyDDNS library is possible to do. Thanks in advance.

**Comment by khoih-prog** [comment]
Sorry, this question has noting to do with this library.

You can create a WebServer using SIM800L if you'd like. I have no time and interest in doing that.

Just search/ask for help on some forums and/or write the WebServer by yourself based on these libraries

1. [**TinyGSM**](https://github.com/vshymanskyy/TinyGSM)
2. [**Arduino-SIM800L-driver**](https://github.com/ostaquet/Arduino-SIM800L-driver)
3. [**SIM800**](https://github.com/aspenforest/SIM800)
4. [**SIM800-for-TCP**](https://github.com/brianrho/SIM800-for-TCP)
